### ISSUE TITLE
Unlock CoA from Legend Game (Dragon)

### ISSUE THREAD

**Issue by victoradriel** [MaximilianFHSTP/max-god#17]
Now it is only unlocking the helmet "Create any legend in the Legend Game." 
It is never unlocking the dragon "Create the legend of Klosterneuburg in the Legend Game."

**Comment by Schlese** [comment]
Please check if the UNLOCK_COA_SYMBOL_ID in the .env has the id 22!

**Comment by Schlese** [comment]
changed id
